name: gbif_bias
version: '1.0.0'
config-version: 2
profile: databricks_gbif

model-paths:  ["models"]
test-paths:   ["tests"]
target-path:  "target"
clean-targets: ["target", "dbt_packages"]

models:
  gbif_bias:
    staging:
      +schema:        staging
      +materialized:  view
    marts:
      +schema:        marts
      +materialized:  table
    metrics:
      +schema:        metrics
      +materialized:  table
